[general]
import = [
  "keybindings.toml",
  "themes/one_dark.toml",
]

[terminal]
shell = { program = "zellij" }
osc52 = "CopyPaste"

[window]
decorations = "None"
padding = { x = 1, y = 1 }
dynamic_padding = true
opacity = 0.96
blur = true

[scrolling]
multiplier = 200

[font]
normal = { family = "Maple Mono NF CN"}
size = 12

[cursor.style]
shape = "Beam"
blinking = "Never"

[mouse]
hide_when_typing = true


